
try :
    print(x)

except :
    print("an error occurred")

finally:
    print("success")

try :
    num1 = 20
    num2 = 10
    print(num1 / num2)

except :
    print("an error occurred")
